In [2]:
pip install numpy       #numpy 다운로드

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------------- ------ 51.2/61.0 kB 871.5 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 806.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   --- ------------------------------------ 1.5/15.8 MB 32.7 MB/s eta 0:00:01
   --------- ------------------------------ 3.8/15.8 MB 40.7 MB/s eta 0:00:01
   --------------- ------------------------ 6.1/15.8 MB 43.3 MB/s eta 0:00:01
   ------------------- -------------------- 7.9/15.8 MB 42.2 MB/s eta 0:00:01
   ------------------------ --------------- 9.6/15.8 MB 43.9 MB/s eta 0:00:01
   ----------------------------- ---------- 11.6/15.8 MB 46.9 MB/s eta 0:00:01
   --------------------------------- ------ 13.3/15.8 MB 46.7 MB/s eta 0:00:01
   ------------------------------------- -- 14.7/15.8 MB 40.9 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 43.7 MB/s eta 

In [2]:
import numpy as np      # numpy를 사용하기 위해 임포트 후 np로 지칭

In [5]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)    #넘파이 배열을 생성
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
data2 = [0.1, 5,4,12,0.5]   #더 큰쪽으로 통일되어서 나오기에 배열을 불러오면 5. , 4.으로 출력됨을 볼 수 있다.
a2= np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [7]:
a1.dtype        #넘파이에서는 .dtype으로 사용하여 데이터타입을 볼 수 있다.

dtype('int32')

In [8]:
a2.dtype

dtype('float64')

In [9]:
np.array([[1,2,3], [4,5,6], [7,8,9]])   # 다차원 배열도 생성가능하다

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)   #np에선 range도 arange로 사용

array([0, 2, 4, 6, 8])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(12).reshape(4,3)  #row4 column3 으로 변경

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
b1 = np.arange(12).reshape(4,3) 
b1.shape    #shape 확인

(4, 3)

In [20]:
b2 = np.arange(5)
b2.shape        #5개의 원소로 이루어진 1차원 배열은 (5,) 으로 표현됨

(5,)

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.linspace(11,20,10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [23]:
np.pi

3.141592653589793

In [22]:
np.linspace(0, np.pi, 20)       # 0 ~ pi 값까지 20개로 나눈 배열을 만들어 줘

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [26]:
np.zeros((3,4))     # 3,4 배열 만들어서 0으로 채워줘

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.eye(3)       #1이 3개나오는 대각배열 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])  # <U8 형식이 유니코드이며 문자의 수는 최대 8개 라는 의미

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [47]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)   #float형으로 캐스팅
num_a2 = num_a1.astype(int)     #int형으로 캐스팅하기 위해선 더블캐스팅이 필요함
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [49]:
num_a2

array([1, 0, 5, 9, 8])

In [50]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [51]:
np.random.rand(2,3)     #2차원 배열 2 * 3 을 만들고 그 안의 값을 램덤(0~1)으로 지정

array([[0.83216811, 0.95483654, 0.76720366],
       [0.7807717 , 0.47548033, 0.13725242]])

In [52]:
np.random.rand()

0.02542792179244746

In [53]:
np.random.rand(2,3,4)

array([[[0.88333327, 0.68584556, 0.15050926, 0.88479654],
        [0.01544588, 0.39230698, 0.94181437, 0.52897753],
        [0.8454488 , 0.82032963, 0.71372708, 0.65480929]],

       [[0.69215592, 0.45567231, 0.92939018, 0.48828553],
        [0.56613314, 0.28655412, 0.46643278, 0.0070859 ],
        [0.96880804, 0.15060615, 0.87279388, 0.28161752]]])

In [54]:
np.random.randint(10, size = (3, 4))        # randint 는 (10까지 , 사이즈는 3 * 4로)

array([[2, 9, 9, 8],
       [8, 4, 1, 8],
       [8, 3, 1, 2]])

In [55]:
arr1 = np.array([10,20,30,40])          #numpy로 만들어진 배열은 사칙연산이 가능하다.
arr2 = np.array([1,2,3,4])

In [62]:
arr1 + arr2

array([11, 22, 33, 44])

In [65]:
arr2 * 2

array([2, 4, 6, 8])

In [64]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [66]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [69]:
arr1 / arr2

array([10., 10., 10., 10.])

In [68]:
arr1 > 20           #각 값이 20보다 큰지 bool타입으로 알려준다 데이터 중 20이상으로 True만 추출해서 사용할 수 있다.

array([False, False,  True,  True])

In [70]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [72]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [73]:
arr3.sum(), arr3.mean()

(10, 2.0)

In [74]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [75]:
[arr3.max(), arr3.min()]

[4, 0]

In [76]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [77]:
arr4.cumsum()   #순차적으로 더해지는 값을 알려줌

array([ 1,  3,  6, 10])

In [78]:
arr4.cumprod()  #순차적으로 곱해지는 값을 알려줌

array([ 1,  2,  6, 24])

In [82]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [83]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [84]:
A.dot(B)            #행렬의 곱

array([[0, 1],
       [6, 7]])

In [85]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [86]:
np.transpose(A)     #전치행렬

array([[0, 2],
       [1, 3]])

In [88]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [90]:
np.linalg.inv(A)    #역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [91]:
np.linalg.det(A)    #행렬식

-2.0

In [92]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [95]:
a1[5] = 70              #배열의 원소를 가져오거나 변경할 수 있다.
a1

array([ 0, 10, 20, 30, 40, 70])

In [96]:
a1[[1,3,4]]     #배열을 한번 더 감싸 n번째 원소를 꺼내올 수 있다.

array([10, 30, 40])

In [97]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [98]:
a2[0,2]

30

In [99]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [100]:
a2[1]

array([40, 50, 60])

In [101]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [102]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [103]:
a2[[0,2], [0,1]]        # [0][0] [2][1]

array([10, 80])

In [104]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [105]:
a[(a%2) == 0]

array([2, 4, 6])

In [106]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [107]:
b1[:3]

array([ 0, 10, 20])

In [108]:
b1[2:]

array([20, 30, 40, 50])

In [110]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [111]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [4]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
b2[1:3, 1:3]        #1행 1열 부터 출력

array([[50, 60],
       [80, 90]])

In [6]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [7]:
b2[1][0:2]

array([40, 50])

In [8]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])