# NumPy
NumPy는 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지이다.

In [2]:
pip install numpy   #numpy를 사용하기위해 다운로드

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 14.0 MB 9.1 MB/s eta 0:00:01
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)    #numpy 배열 생성
data1

[0, 1, 2, 3, 4, 5]

In [6]:
a1.dtype    #numpy에서는 type앞에 d를 붙여 타입을 확인한다.

dtype('int64')

In [7]:
np.array([[1,2,3], [4,5,6], [7,8,9]])   #다차원 배열도 생성할 수 있다.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#범위를 지정한 배열 생성
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(12).reshape(4,3)  #reshape(m,n)를하면 m * n 의배열을 생성

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
b1 = np.arange(12).reshape(4,3)
b1.shape    #shape를 사용하여 배열의 형태를 확인할 수 있다.

(4, 3)

In [11]:
#linspace(start, end, n )는 시작점부터 끝점까지 n개의 배열을 생성한다.
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

모든 원소가 0이나 1인 다차원 배열을 만들기위해선 zero()나 ones()를 이용할 수 있다.

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#단위행렬생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
#NumPy배열의 문자열을 숫자(정수나 실수)로 캐스팅하여 연산이 필요할때가 존재한다.
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [5]:
str_a1.dtype

dtype('<U5')

In [7]:
num_a1.dtype    #float형으로 캐스팅된걸 확인할 수 있음.

dtype('float64')

In [8]:
# 2*3 램덤 난수생성 (0 ~ 1) 사이의 실수로 난수 생성
np.random.rand(2,3) 

array([[0.89493501, 0.59339822, 0.92344977],
       [0.76458146, 0.4624132 , 0.47583807]])

In [9]:
np.random.randint(10,size=(3,4))    #모양과 범위 모두 정해줄 수 있다.

array([[1, 8, 0, 5],
       [0, 6, 3, 0],
       [6, 5, 2, 8]])

### 배열의 연산
NumPy 배열은 연산이 가능하다. 배열의 형태가 같다면 덧셈과 뺄셈, 곱셈과 나눗셈 연산이 가능하다.

In [10]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [11]:
arr1 + arr2

array([11, 22, 33, 44])

In [12]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [13]:
arr2 * 2

array([2, 4, 6, 8])

In [14]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [15]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [16]:
arr1 / arr2

array([10., 10., 10., 10.])

In [17]:
# 비교연산을 통한 bool값 출력
arr1 > 20

array([False, False,  True,  True])

In [18]:
arr3 = np.arange(5) #NumPy에서의 range도 앞에 a를 붙여 arange()로 사용
arr3

array([0, 1, 2, 3, 4])

In [20]:
[arr3.sum(), arr3.mean()]   #arr3의 합과 평균

[10, 2.0]

In [22]:
[arr3.std(), arr3.var()]    #arr3의 표준편차와 분산

[1.4142135623730951, 2.0]

In [23]:
[arr3.min(), arr3.max()]    #arr3의 최솟값과 최댓값

[0, 4]

In [24]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [25]:
arr4.cumsum()   #누적합

array([ 1,  3,  6, 10])

In [26]:
arr4.cumprod()  #누적곱

array([ 1,  2,  6, 24])

### 행렬 연산

In [27]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [29]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [30]:
A.dot(B)    #A와 B를 이용한 행렬의 곱

array([[0, 1],
       [6, 7]])

In [32]:
A.transpose()   #A의 전치행렬

array([[0, 2],
       [1, 3]])

In [33]:
np.linalg.inv(A) #A의 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [34]:
np.linalg.det(A) #의 행렬식

-2.0

### 배열의 인덱싱과 슬라이싱

In [35]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [36]:
a1[0]

0

In [37]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [38]:
a1[[1,3,4]]

array([10, 30, 40])

In [39]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
a2[0,2]

30

In [41]:
a2[2,2] = 95    #배열을 자유롭게 바꾸거나 꺼내올 수 있다.
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [42]:
a = np.array([1,2,3,4,5,6])
a[a > 3]    #배열 a안에서 3이상의 값만 추출도 가능

array([4, 5, 6])

In [43]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4] #배열의 시작과 끝을 적어 슬라이싱 가능

array([10, 20, 30])

# pnadas

In [2]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.8/114.8 kB 3.7 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 3.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 2.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 4.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 4.6 MB/s eta 0:00:00 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

Series()를 이용하여 pnadas의 가장 기본적인 방법인 Series 형식의 구조적 데이터를 생성할 수 있다

In [4]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
print(s1.index) #Series는 index와 values를 분리해서 가져올 수 있다.
print(s1.values)

RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]


In [7]:
#딕셔너리를 이용하면 데이터와 index를 이용하면 데이터와 index를 함꼐 입력할 수 있다.
s2 = pd.Series({'국어':100, '영어':95, '수학':90})
s2  #key값이 index값과 동일함을 알 수 있다.

국어    100
영어     95
수학     90
dtype: int64

In [8]:
#날짜 자동 생성 date_range

pd.date_range(start='2019-01-01',end='2019.01.07')  #날짜의 구분자는 - / . 모두 사용가능하지만 생성된 데이터는 모두 -로 출력된다.

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [9]:
pd.date_range(start='2019.01.01', periods = 7)  #freq를 적지 않아 기본적으로'D'가 지정되어 하루씩 증가한다.

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [11]:
#date_range()를 이용해 Series의 index를 지정한 예
index_data = pd.date_range(start = '2019.03.01', periods=5, freq='D')
pd.Series([51,62,55,49,58], index = index_data)

2019-03-01    51
2019-03-02    62
2019-03-03    55
2019-03-04    49
2019-03-05    58
Freq: D, dtype: int64

In [12]:
#DataFrame을 활용한 데이터 생성
#리스트를 이용한 DataFrame생성
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
#NumPy의 배열을 입력해 생성한 DataFrame
data_list = np.array([[10,20,30],[40,50,60],[70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [14]:
# index와 columns 지정

data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index_data = pd.date_range('2019/09/01', periods=4)
columns_list = ['A', 'B', 'C']
pd.DataFrame(data, index = index_data, columns = columns_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

In [15]:
#딕셔너리데이터를 이용한 DataFrame 생성

table_data = {'연도' : [2015, 2016, 2016, 2017, 2017],
              '지사' : ['한국', '한국', '미국', '한국', '미국'],
              '고객 수' : [200, 250, 450, 300, 500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [16]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [18]:
df = pd.DataFrame(table_data, columns=['연도', '지사', '고객 수']) #키의 순서를 지정할 수 있다.
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [19]:
#데이터의 연산
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
s1 + s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [20]:
s2 - s1

0     9
1    18
2    27
3    36
4    45
dtype: int64

In [21]:
#pandas는 NumPy와 달리 서로 길이가 달라도 연산할 수 있다.
s3 = pd.Series([1,2,3,4])
s4 = pd.Series([10,20,30,40,50])
s3 + s4 #연산할 수 없는 부분은 NaN으로 표시한다.

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [22]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [23]:
df3.mean() #평균

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [24]:
df3.std() #표준 편차

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [25]:
df3.mean(axis=1) #열 방향 평균

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [26]:
df3.std(axis=1) #열 방향 표준편차

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [27]:
df3.describe()  #describe를 이용하면 평균 표준편차 최솟값 최댓값을 한번에 구할 수 있다.

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [28]:
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [31]:
print(df_KTX.index)
print(df_KTX.columns)
print(df_KTX.values)

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')
Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')
[[39060.  7313.  3627.   309.    nan]
 [39896.  6967.  4168.  1771.    nan]
 [42005.  6873.  4088.  1954.    nan]
 [43621.  6626.  4424.  2244.    nan]
 [41702.  8675.  4606.  3146.  2395.]
 [41266. 10622.  4984.  3945.  3786.]
 [32427.  9228.  5570.  5766.  6667.]]


In [32]:
df_KTX.head()   #데이터의 첫 5개의 행 데이터

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [33]:
df_KTX.tail()   #데이터의 마지막 5개의 행 데이터

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [34]:
#tail,head의 괄호안에 인자를 정해 원하는 개수의 행 데이터를 반환할 수 있다.
df_KTX.head(3)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN

In [35]:
df_KTX[1:2] #시작과 끝의 위치를 정해 출력할 수 있다.

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN

In [36]:
df_KTX[2:5]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0